### PR TITLE
Add inheritance to site configuration

### PR DESCRIPTION
**Pull request by andytson**
This is to be able to share config across multiple
sites, even on the same environment.

### CODE REVIEW

**Comment by mikesimons** [comment]
I have tested this PR and it works great except for encapsulation failure where sites data needs to be accessible outside of app_vhost.

I am investigating options to mitigate this before merging.

**Comment by andytson** [comment]
@mikesimons I've just added enough to stop needing to re-implement the site data merge outside of the definition.

**Comment by incubator-inviqa** [comment]
Can one of the admins verify this patch?

**Comment by shrikeh** [comment]
@andytson can you give this a quick branch refresh please?

**Comment by andytson** [comment]
@shrikeh done

**Pull request merged**
